### ISSUE TITLE
Missing MIT.md file

### ISSUE THREAD

**Issue by emmiiorji** [microverseinc/curriculum-databases-projects-template#1]
Hi,

Thanks for the nice template.

The instruction in README file says to not add files unless mentioned. However, the [MIT.md](https://github.com/microverseinc/curriculum-template-databases/commit/62926247d2328dab144e7b740f76f6e1d920d5d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R47-R48) linked seems to be missing.

Could it be added to the template?

**Comment by pat-gonzalez** [comment]
Hello, emmiiorji. Thank you for the report. We are working on this and will add the link. It might take a couple of days, though!

Happy learning,
Paty

**Comment by emmiiorji** [comment]
Okay, that'll be great.

Thank you.

**Comment by nidalaa** [comment]
Hello @emmiiorji 

Thank you for your report. It took us a while to get to this as our backlog is pretty big right now.
However, the good news is - we update the README template to include additional information about licenses. The file is still empty - as the license needs to be created by the author of the code but we left are now showing you how to set that up quickly.

Once again - thank you for reporting this! ❤️
