### ISSUE TITLE
Update Readme file 

### ISSUE THREAD

**Issue by Davidosky007** [microverseinc/curriculum-databases-projects-template#3]
Hi 👋,
I suggest the readme template be updated to the [current one used](https://github.com/microverseinc/readme-template) so that all projects will have the same updated readme templates.

**Comment by bellom** [comment]
@nidalaa

**Comment by nidalaa** [comment]
Good call @Davidosky007  - can you open a a PR?

**Comment by bellom** [comment]
@nidalaa - kindly check this [MR](https://gitlab.com/microverse/guides/tse/code_review/code_review_guidelines_2_0/-/merge_requests/211) to better understand the situation.

I think we need to redesign the README template for Database project.

**Comment by Davidosky007** [comment]
> Good call @Davidosky007 - can you open a a PR?

I can not open a PR unless i fork this repo

**Comment by nidalaa** [comment]
@bellom checked :) What we need to do is to update the README in database-template :)

**Comment by nidalaa** [comment]
@Davidosky007  and @bellom  access granted - you can open Prs now :)

**Comment by Davidosky007** [comment]
> @Davidosky007 and @bellom access granted - you can open Prs now :)

i will do that now @nidalaa thanks 🙏

**Comment by bellom** [comment]
@nidalaa - done by @Davidosky007 - [PR](https://github.com/microverseinc/curriculum-template-databases/pull/4)

**Comment by bellom** [comment]
We can close this issue now, PR created.
